const fs = require('fs');
const html = fs.readFileSync('index.html', 'utf8');
const scriptMatch = html.match(/<script>([\s\S]*?)<\/script>/);
global.window = { innerWidth: 1920, innerHeight: 1080, addEventListener: () => {}, AudioContext: class { constructor() { this.currentTime=0; this.state='running'; this.destination={}; } createGain() { return { gain: { setValueAtTime: ()=>{}, exponentialRampToValueAtTime: ()=>{}, linearRampToValueAtTime: ()=>{}, setTargetAtTime: ()=>{} }, connect: ()=>{} }; } createOscillator() { return { frequency: { setValueAtTime: ()=>{}, exponentialRampToValueAtTime: ()=>{} }, connect: ()=>{}, start: ()=>{}, stop: ()=>{} }; } createBiquadFilter() { return { frequency: { setValueAtTime: ()=>{}, exponentialRampToValueAtTime: ()=>{} }, Q: { setValueAtTime: ()=>{} }, connect: ()=>{} }; } resume() {} } };
global.document = { getElementById: () => ({ getContext: () => ({ save: ()=>{}, restore: ()=>{}, translate: ()=>{}, scale: ()=>{}, rotate: ()=>{}, fillRect: ()=>{}, strokeRect: ()=>{}, beginPath: ()=>{}, arc: ()=>{}, ellipse: ()=>{}, moveTo: ()=>{}, lineTo: ()=>{}, stroke: ()=>{}, fill: ()=>{}, closePath: ()=>{}, drawImage: ()=>{}, clearRect: ()=>{}, fillText: ()=>{}, setLineDash: ()=>{}, clip: ()=>{}, createLinearGradient: () => ({ addColorStop: ()=>{} }), createRadialGradient: () => ({ addColorStop: ()=>{} }) }), style: {}, addEventListener: ()=>{}, getBoundingClientRect: () => ({ left: 0, top: 0, width: 960, height: 540 }) }) };
global.Image = class { constructor() { this.complete = true; this.naturalWidth = 256; this.naturalHeight = 256; } };
global.navigator = { maxTouchPoints: 0 };
global.requestAnimationFrame = (cb) => setTimeout(cb, 16);
global.performance = { now: () => Date.now() };
eval(scriptMatch[1]);
const CG = window.CommuterGame;
const { Game } = CG;
const game = new Game();
game.startGame();
const coins = game.pm.items.filter(i => i.type === 'coin');
console.log('Total coins:', coins.length);
console.log('Coins up to 3500 (S1):', coins.filter(c => c.x <= 3500).length);
console.log('Coins up to 7000 (S2):', coins.filter(c => c.x <= 7000).length);
console.log('Coins up to 10500 (S3):', coins.filter(c => c.x <= 10500).length);
console.log('Ground coins up to 7000:', coins.filter(c => c.x <= 7000 && c.y > 500).length);
console.log('Platform coins up to 7000:', coins.filter(c => c.x <= 7000 && c.y <= 500).length);
console.log('Ground coins up to 10500:', coins.filter(c => c.x <= 10500 && c.y > 500).length);
